#import "Kiwi.h"
#import "HandlerMock.h"
#import "ACAccountStore+AsyncResult.h"


@interface ACAccountStoreMock : ACAccountStore
@property (nonatomic) NSString* method;
@property (nonatomic) id handler;
- (void)requestAccessToAccountsWithType:(ACAccountType *)accountType withCompletionHandler:(ACAccountStoreRequestAccessCompletionHandler)handler;
- (void)requestAccessToAccountsWithType:(ACAccountType *)accountType options:(NSDictionary *)options completion:(ACAccountStoreRequestAccessCompletionHandler)completion;
- (void)renewCredentialsForAccount:(ACAccount *)account completion:(ACAccountStoreCredentialRenewalHandler)completionHandler;
- (void)removeAccount:(ACAccount *)account withCompletionHandler:(ACAccountStoreRemoveCompletionHandler)completionHandler;
@end

@implementation ACAccountStoreMock
- (void)requestAccessToAccountsWithType:(ACAccountType *)accountType withCompletionHandler:(ACAccountStoreRequestAccessCompletionHandler)handler
{
    self.handler = handler;
    self.method  = @"requestAccessToAccountsWithType:withCompletionHandler:";
}
- (void)requestAccessToAccountsWithType:(ACAccountType *)accountType options:(NSDictionary *)options completion:(ACAccountStoreRequestAccessCompletionHandler)completion
{
    self.handler = completion;
    self.method  = @"requestAccessToAccountsWithType:options:completion:";
}
- (void)renewCredentialsForAccount:(ACAccount *)account completion:(ACAccountStoreCredentialRenewalHandler)completionHandler
{
    self.handler = completionHandler;
    self.method  = @"renewCredentialsForAccount:completion:";
}
- (void)removeAccount:(ACAccount *)account withCompletionHandler:(ACAccountStoreRemoveCompletionHandler)completionHandler
{
    self.handler = completionHandler;
    self.method  = @"removeAccount:withCompletionHandler:";
}
@end


SPEC_BEGIN(ACAccountStoreSpec)

describe(@"AsyncResult generated by", ^{
    registerMatchers(@"AR");

    __block id<AsyncResult>     result  = nil;
    __block HandlerMock*        handler = nil;
    __block ACAccountStoreMock* mock    = nil;
    __block ACAccountType*      accType = nil;
    __block ACAccount*          account = nil;

    beforeEach(^{
        handler = [[HandlerMock alloc] init];
        mock    = [[ACAccountStoreMock alloc] init];
        accType = [mock accountTypeWithAccountTypeIdentifier:ACAccountTypeIdentifierTwitter];
        account = [[ACAccount alloc] initWithAccountType:accType];
    });

    afterEach(^{
        result  = nil;
        handler = [handler clear];
        mock    = nil;
        accType = nil;
        account = nil;
    });

    context(@"requestAccessToAccountsWithType:", ^{

        it(@"should success when twitter account access is granted", ^{
            result = [mock requestAccessToAccountsWithType:accType];
            asyncWait(result, handler.block);

            void(^callback)(BOOL, NSError*) = mock.handler;
            callback(YES, nil);

            [[handler should] beCalledWithValue:mock result:result onMainThread:YES];
            [[mock.method should] equal:@"requestAccessToAccountsWithType:withCompletionHandler:"];
        });

        it(@"should error when twitter account access is rejected", ^{
            result = [mock requestAccessToAccountsWithType:accType];
            asyncWait(result, handler.block);

            void(^callback)(BOOL, NSError*) = mock.handler;
            NSError* error = [[NSError alloc] initWithDomain:ACErrorDomain code:ACErrorPermissionDenied userInfo:nil];
            callback(NO, error);

            NSDictionary* value = @{ @"accountStore":mock, @"error":error };
            [[handler should] beCalledWithError:value result:result onMainThread:YES];
            [[mock.method should] equal:@"requestAccessToAccountsWithType:withCompletionHandler:"];
        });

        it(@"should error when twitter account access is rejected even without error information", ^{
            result = [mock requestAccessToAccountsWithType:accType];
            asyncWait(result, handler.block);

            void(^callback)(BOOL, NSError*) = mock.handler;
            callback(NO, nil);

            NSDictionary* value = @{ @"accountStore":mock };
            [[handler should] beCalledWithError:value result:result onMainThread:YES];
            [[mock.method should] equal:@"requestAccessToAccountsWithType:withCompletionHandler:"];
        });

    });

    context(@"requestAccessToAccountsWithType:options:", ^{

        it(@"should success when twitter account access is granted", ^{
            result = [mock requestAccessToAccountsWithType:accType options:nil];
            asyncWait(result, handler.block);

            void(^callback)(BOOL, NSError*) = mock.handler;
            callback(YES, nil);

            [[handler should] beCalledWithValue:mock result:result onMainThread:YES];
            [[mock.method should] equal:@"requestAccessToAccountsWithType:options:completion:"];
        });

        it(@"should error when twitter account access is rejected", ^{
            result = [mock requestAccessToAccountsWithType:accType options:nil];
            asyncWait(result, handler.block);

            void(^callback)(BOOL, NSError*) = mock.handler;
            NSError* error = [[NSError alloc] initWithDomain:ACErrorDomain code:ACErrorPermissionDenied userInfo:nil];
            callback(NO, error);

            NSDictionary* value = @{ @"accountStore":mock, @"error":error };
            [[handler should] beCalledWithError:value result:result onMainThread:YES];
            [[mock.method should] equal:@"requestAccessToAccountsWithType:options:completion:"];
        });

        it(@"should error when twitter account access is rejected even without error information", ^{
            result = [mock requestAccessToAccountsWithType:accType options:nil];
            asyncWait(result, handler.block);

            void(^callback)(BOOL, NSError*) = mock.handler;
            callback(NO, nil);

            NSDictionary* value = @{ @"accountStore":mock };
            [[handler should] beCalledWithError:value result:result onMainThread:YES];
            [[mock.method should] equal:@"requestAccessToAccountsWithType:options:completion:"];
        });

    });

    context(@"renewCredentialsForAccount:", ^{

        it(@"should success when the account is renewed", ^{
            result = [mock renewCredentialsForAccount:account];
            asyncWait(result, handler.block);

            void(^callback)(ACAccountCredentialRenewResult, NSError*) = mock.handler;
            callback(ACAccountCredentialRenewResultRenewed, nil);

            [[handler should] beCalledWithValue:account result:result onMainThread:YES];
            [[mock.method should] equal:@"renewCredentialsForAccount:completion:"];
        });

        it(@"should error when renewing the account is rejected", ^{
            result = [mock renewCredentialsForAccount:account];
            asyncWait(result, handler.block);

            void(^callback)(ACAccountCredentialRenewResult, NSError*) = mock.handler;
            NSError* error = [[NSError alloc] initWithDomain:ACErrorDomain code:ACErrorPermissionDenied userInfo:nil];
            callback(ACAccountCredentialRenewResultRejected, error);

            NSDictionary* value = @{ @"accountStore":mock, @"account":account, @"renewResult":[[NSNumber alloc] initWithInteger:ACAccountCredentialRenewResultRejected], @"error":error };
            [[handler should] beCalledWithError:value result:result onMainThread:YES];
            [[mock.method should] equal:@"renewCredentialsForAccount:completion:"];
        });

        it(@"should error when renewing the account is rejected even without error information", ^{
            result = [mock renewCredentialsForAccount:account];
            asyncWait(result, handler.block);

            void(^callback)(ACAccountCredentialRenewResult, NSError*) = mock.handler;
            callback(ACAccountCredentialRenewResultFailed, nil);

            NSDictionary* value = @{ @"accountStore":mock, @"account":account, @"renewResult":[[NSNumber alloc] initWithInteger:ACAccountCredentialRenewResultFailed] };
            [[handler should] beCalledWithError:value result:result onMainThread:YES];
            [[mock.method should] equal:@"renewCredentialsForAccount:completion:"];
        });

    });

    context(@"removeAccount:", ^{

        it(@"should success when the account is deleted", ^{
            result = [mock removeAccount:account];
            asyncWait(result, handler.block);

            void(^callback)(BOOL, NSError*) = mock.handler;
            callback(YES, nil);

            [[handler should] beCalledWithValue:account result:result onMainThread:YES];
            [[mock.method should] equal:@"removeAccount:withCompletionHandler:"];
        });

        it(@"should error when renewing the account is rejected", ^{
            result = [mock removeAccount:account];
            asyncWait(result, handler.block);

            void(^callback)(BOOL, NSError*) = mock.handler;
            NSError* error = [[NSError alloc] initWithDomain:ACErrorDomain code:ACErrorAccountNotFound userInfo:nil];
            callback(NO, error);

            NSDictionary* value = @{ @"accountStore":mock, @"account":account, @"error":error };
            [[handler should] beCalledWithError:value result:result onMainThread:YES];
            [[mock.method should] equal:@"removeAccount:withCompletionHandler:"];
        });

        it(@"should error when renewing the account is rejected even without error information", ^{
            result = [mock removeAccount:account];
            asyncWait(result, handler.block);

            void(^callback)(BOOL, NSError*) = mock.handler;
            callback(NO, nil);

            NSDictionary* value = @{ @"accountStore":mock, @"account":account };
            [[handler should] beCalledWithError:value result:result onMainThread:YES];
            [[mock.method should] equal:@"removeAccount:withCompletionHandler:"];
        });
        
    });

});

SPEC_END
